import type {
  MockUser,
  MockCampaign,
  MockItem,
  MockSpell,
  MockMonster,
  MockCharacter,
  MockSession,
  MockNotes,
} from "@/types/mockup";

// Mock Authentication Data
export const mockUser: MockUser = {
  id: 1,
  username: "dmmaster",
  email: "dm@dungeon.com",
  name: "Master DM",
};

// Mock Campaigns Data
export const mockCampaigns: MockCampaign[] = [
  {
    id: 1,
    name: "The Lost Mines of Phandelver",
    description: "A classic adventure for new players exploring goblin-infested ruins.",
    players: 4,
    level: "1-5",
    sessions: 8,
    lastPlayed: "2024-01-15",
    thumbnail:
      "https://images.pexels.com/photos/1002638/pexels-photo-1002638.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&fit=crop",
  },
  {
    id: 2,
    name: "Curse of Strahd",
    description: "A gothic horror adventure in the mist-shrouded lands of Barovia.",
    players: 5,
    level: "1-10",
    sessions: 15,
    lastPlayed: "2024-01-12",
    thumbnail:
      "https://images.pexels.com/photos/1557652/pexels-photo-1557652.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&fit=crop",
  },
  {
    id: 3,
    name: "Storm Kings Thunder",
    description: "Giants have emerged from their strongholds to threaten civilization.",
    players: 6,
    level: "1-11",
    sessions: 22,
    lastPlayed: "2024-01-08",
    thumbnail:
      "https://images.pexels.com/photos/1000445/pexels-photo-1000445.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&fit=crop",
  },
];

// Mock Items Data
export const mockItems: MockItem[] = [
  {
    id: 1,
    name: "Longsword +1",
    type: "Weapon",
    rarity: "Uncommon",
    price: "1,000 gp",
    description: "A magical longsword with a +1 bonus to attack and damage rolls.",
  },
  {
    id: 2,
    name: "Potion of Healing",
    type: "Potion",
    rarity: "Common",
    price: "50 gp",
    description: "Restores 2d4+2 hit points when consumed.",
  },
  {
    id: 3,
    name: "Bag of Holding",
    type: "Wondrous Item",
    rarity: "Uncommon",
    price: "4,000 gp",
    description: "A magical bag that can hold much more than its size suggests.",
  },
  {
    id: 4,
    name: "Ring of Protection",
    type: "Ring",
    rarity: "Rare",
    price: "8,000 gp",
    description: "Grants a +1 bonus to AC and saving throws.",
  },
  {
    id: 5,
    name: "Cloak of Elvenkind",
    type: "Wondrous Item",
    rarity: "Uncommon",
    price: "5,000 gp",
    description: "Provides advantage on Dexterity (Stealth) checks.",
  },
  {
    id: 6,
    name: "Flame Tongue",
    type: "Weapon",
    rarity: "Rare",
    price: "12,000 gp",
    description: "A sword that can burst into flames on command.",
  },
  {
    id: 7,
    name: "Boots of Speed",
    type: "Wondrous Item",
    rarity: "Rare",
    price: "15,000 gp",
    description: "Doubles your speed for 10 minutes once per day.",
  },
  {
    id: 8,
    name: "Shield +2",
    type: "Armor",
    rarity: "Rare",
    price: "6,000 gp",
    description: "A magical shield with a +2 bonus to AC.",
  },
  {
    id: 9,
    name: "Wand of Magic Missiles",
    type: "Wand",
    rarity: "Uncommon",
    price: "8,000 gp",
    description: "Can cast Magic Missile spell with 7 charges.",
  },
  {
    id: 10,
    name: "Elven Chain",
    type: "Armor",
    rarity: "Rare",
    price: "20,000 gp",
    description: "Chain mail that can be worn under normal clothes.",
  },
];

// Mock Spells Data
export const mockSpells: MockSpell[] = [
  {
    id: 1,
    name: "Fireball",
    level: 3,
    school: "Evocation",
    castingTime: "1 action",
    range: "150 feet",
    classes: ["Sorcerer", "Wizard"],
    description: "A bright flash of fire erupts from your finger, dealing 8d6 fire damage in a 20-foot radius.",
  },
  {
    id: 2,
    name: "Heal",
    level: 6,
    school: "Evocation",
    castingTime: "1 action",
    range: "Touch",
    classes: ["Cleric", "Druid"],
    description: "Choose a creature you touch. The target regains 70 hit points.",
  },
  {
    id: 3,
    name: "Magic Missile",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    classes: ["Sorcerer", "Wizard"],
    description: "Three glowing darts of magical force that automatically hit their target.",
  },
  {
    id: 4,
    name: "Shield",
    level: 1,
    school: "Abjuration",
    castingTime: "1 reaction",
    range: "Self",
    classes: ["Sorcerer", "Wizard"],
    description: "An invisible barrier of magical force appears, granting +5 AC until start of next turn.",
  },
  {
    id: 5,
    name: "Cure Wounds",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "Touch",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    description: "Touch a creature to restore 1d8 + spellcasting modifier hit points.",
  },
  {
    id: 6,
    name: "Lightning Bolt",
    level: 3,
    school: "Evocation",
    castingTime: "1 action",
    range: "100 feet",
    classes: ["Sorcerer", "Wizard"],
    description: "A stroke of lightning forming a 100-foot line deals 8d6 lightning damage.",
  },
  {
    id: 7,
    name: "Counterspell",
    level: 3,
    school: "Abjuration",
    castingTime: "1 reaction",
    range: "60 feet",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    description: "Interrupt a creature casting a spell to prevent its effects.",
  },
  {
    id: 8,
    name: "Teleport",
    level: 7,
    school: "Conjuration",
    castingTime: "1 action",
    range: "10 feet",
    classes: ["Bard", "Sorcerer", "Wizard"],
    description: "Instantly transport up to 8 creatures to a familiar destination.",
  },
  {
    id: 9,
    name: "Dispel Magic",
    level: 3,
    school: "Abjuration",
    castingTime: "1 action",
    range: "120 feet",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Warlock", "Wizard"],
    description: "End one magical effect of 3rd level or lower on a target.",
  },
  {
    id: 10,
    name: "Wish",
    level: 9,
    school: "Conjuration",
    castingTime: "1 action",
    range: "Self",
    classes: ["Sorcerer", "Wizard"],
    description: "The most powerful spell, grants any wish within reason.",
  },
];

// Mock Monsters Data
export const mockMonsters: MockMonster[] = [
  {
    id: 1,
    name: "Ancient Red Dragon",
    cr: 24,
    type: "Dragon",
    size: "Gargantuan",
    hp: 546,
    ac: 22,
    description: "The most cunning and treacherous of chromatic dragons.",
  },
  {
    id: 2,
    name: "Goblin",
    cr: 0.25,
    type: "Humanoid",
    size: "Small",
    hp: 7,
    ac: 15,
    description: "Small, black-hearted creatures that gather in tribes.",
  },
  {
    id: 3,
    name: "Owlbear",
    cr: 3,
    type: "Monstrosity",
    size: "Large",
    hp: 59,
    ac: 13,
    description: "A cross between a giant owl and a bear.",
  },
  {
    id: 4,
    name: "Beholder",
    cr: 13,
    type: "Aberration",
    size: "Large",
    hp: 180,
    ac: 18,
    description: "A floating orb with a large mouth, single central eye, and many eyestalks.",
  },
  {
    id: 5,
    name: "Mind Flayer",
    cr: 7,
    type: "Aberration",
    size: "Medium",
    hp: 71,
    ac: 15,
    description: "Brain-eating aberrations that enslave other creatures.",
  },
  {
    id: 6,
    name: "Tarrasque",
    cr: 30,
    type: "Monstrosity",
    size: "Gargantuan",
    hp: 676,
    ac: 25,
    description: "The most dreaded monster of the Material Plane.",
  },
  {
    id: 7,
    name: "Orc",
    cr: 0.5,
    type: "Humanoid",
    size: "Medium",
    hp: 15,
    ac: 13,
    description: "Savage raiders and pillagers with stooped postures.",
  },
  {
    id: 8,
    name: "Troll",
    cr: 5,
    type: "Giant",
    size: "Large",
    hp: 84,
    ac: 15,
    description: "Regenerating giants with long claws and fangs.",
  },
  {
    id: 9,
    name: "Lich",
    cr: 21,
    type: "Undead",
    size: "Medium",
    hp: 135,
    ac: 17,
    description: "A powerful spellcaster who achieved undeath through dark magic.",
  },
  {
    id: 10,
    name: "Basilisk",
    cr: 3,
    type: "Monstrosity",
    size: "Medium",
    hp: 52,
    ac: 12,
    description: "A reptilian monster whose gaze turns creatures to stone.",
  },
];

// Mock Characters Data
export const mockCharacters: Record<number, MockCharacter[]> = {
  1: [
    // Campaign 1 characters
    {
      id: 1,
      name: "Thorin Ironforge",
      class: "Fighter",
      level: 3,
      race: "Dwarf",
      hp: 34,
      maxHp: 34,
      ac: 18,
      str: 16,
      dex: 12,
      con: 16,
      int: 10,
      wis: 13,
      cha: 8,
    },
    {
      id: 2,
      name: "Elaria Moonwhisper",
      class: "Wizard",
      level: 3,
      race: "Elf",
      hp: 22,
      maxHp: 22,
      ac: 13,
      str: 8,
      dex: 14,
      con: 13,
      int: 17,
      wis: 12,
      cha: 10,
    },
    {
      id: 3,
      name: "Finn Lightfinger",
      class: "Rogue",
      level: 3,
      race: "Halfling",
      hp: 26,
      maxHp: 26,
      ac: 15,
      str: 10,
      dex: 17,
      con: 12,
      int: 14,
      wis: 13,
      cha: 12,
    },
    {
      id: 4,
      name: "Sister Seraphina",
      class: "Cleric",
      level: 3,
      race: "Human",
      hp: 28,
      maxHp: 28,
      ac: 16,
      str: 12,
      dex: 10,
      con: 14,
      int: 11,
      wis: 16,
      cha: 14,
    },
  ],
  2: [
    // Campaign 2 characters
    {
      id: 5,
      name: "Valdric Shadowbane",
      class: "Paladin",
      level: 5,
      race: "Human",
      hp: 52,
      maxHp: 52,
      ac: 20,
      str: 18,
      dex: 10,
      con: 16,
      int: 10,
      wis: 12,
      cha: 16,
    },
    {
      id: 6,
      name: "Zara Wildstorm",
      class: "Barbarian",
      level: 5,
      race: "Half-Orc",
      hp: 68,
      maxHp: 68,
      ac: 14,
      str: 18,
      dex: 14,
      con: 18,
      int: 8,
      wis: 12,
      cha: 10,
    },
    {
      id: 7,
      name: "Melody Songweaver",
      class: "Bard",
      level: 5,
      race: "Half-Elf",
      hp: 42,
      maxHp: 42,
      ac: 14,
      str: 10,
      dex: 14,
      con: 14,
      int: 12,
      wis: 11,
      cha: 18,
    },
  ],
};

// Mock Session Data
export const mockSessions: Record<number, MockSession[]> = {
  1: [
    {
      id: 1,
      date: "2024-01-15",
      title: "The Goblin Ambush",
      participants: ["Thorin", "Elaria", "Finn", "Sister Seraphina"],
      summary: "The party encountered goblins on the Triboar Trail and rescued Sildar Hallwinter.",
    },
    {
      id: 2,
      date: "2024-01-08",
      title: "Exploring Phandalin",
      participants: ["Thorin", "Elaria", "Finn"],
      summary: "Arrived in Phandalin and met several key NPCs including Toblen Stonehill.",
    },
    {
      id: 3,
      date: "2024-01-01",
      title: "Character Creation",
      participants: ["Thorin", "Elaria", "Finn", "Sister Seraphina"],
      summary: "Session 0 - Created characters and established party bonds.",
    },
  ],
  2: [
    {
      id: 4,
      date: "2024-01-12",
      title: "The Mists of Barovia",
      participants: ["Valdric", "Zara", "Melody"],
      summary: "First encounter with the mysterious mists and arrival at the village of Barovia.",
    },
    {
      id: 5,
      date: "2024-01-05",
      title: "Death House",
      participants: ["Valdric", "Zara", "Melody"],
      summary: "Explored the haunted mansion and uncovered dark family secrets.",
    },
  ],
};

// Mock Notes Data
export const mockNotes: Record<number, MockNotes> = {
  1: {
    npcs: [
      {
        id: 1,
        name: "Gundren Rockseeker",
        role: "Quest Giver",
        location: "Phandalin",
        notes: "Dwarf merchant who hired the party. Brother to Nundro and Tharden.",
      },
      {
        id: 2,
        name: "Sildar Hallwinter",
        role: "Ally",
        location: "Phandalin",
        notes: "Lords Alliance agent. Grateful to the party for rescue.",
      },
    ],
    locations: [
      {
        id: 1,
        name: "Phandalin",
        type: "Town",
        description: "Small frontier town built on the ruins of an older settlement.",
      },
      { id: 2, name: "Cragmaw Hideout", type: "Dungeon", description: "Goblin cave complex near the Triboar Trail." },
    ],
    quests: [
      {
        id: 1,
        name: "Find Gundren Rockseeker",
        status: "Active",
        description: "Locate the missing dwarf and his wagon.",
      },
      { id: 2, name: "Clear out Cragmaw Hideout", status: "Completed", description: "Eliminate the goblin threat." },
    ],
  },
};
